---
services:
- calc-db
- calc-env
- calc-redis
applications:
- name: calc-sandbox
  instances: 1
  memory: 256M
  disk_quota: 1024M
  host: calc-sandbox
  domain: apps.cloud.gov
  buildpack: python_buildpack
  command: bash cf.sh
  stack: cflinuxfs2
  timeout: 180
- name: calc-rqworker
  no-route: true
  instances: 1
  memory: 256M
  buildpack: python_buildpack
  command: python manage.py rqworker default
  stack: cflinuxfs2
  timeout: 180
  env:
    DISABLE_COLLECTSTATIC: "1"
- name: calc-rqscheduler
  no-route: true
  instances: 1
  memory: 256M
  buildpack: python_buildpack
  command: python manage.py rqscheduler
  stack: cflinuxfs2
  timeout: 180
  env:
    IS_RQ_SCHEDULER: "yup"
    DISABLE_COLLECTSTATIC: "1"
